<?php
$title = "Delete " . $this->video->getName() . "?";
$this->headTitle($title);
?>

<div class="container">
    <p class="alert alert-info"><strong>INFO: </strong>This will not delete the video permanently, just the MediaBox reference.</p>
    <p class="alert alert-warning"><strong>TIP: </strong>You can untag your department if other departments are still listed against the video</p>
    <h1><?= $this->escapeHtml($title) ?></h1>

    <p>Are you sure you wish to delete "<?= $this->video->getName() ?>" from MediaBox?</p>
    <form action="<?= $url ?>" method="post">
        <div class="form-group">
            <input type="hidden" name="id" value="<?= (int) $this->video->getId() ?>" />
            <input type="submit" class="btn btn-success" name="del" value="Yes" />
            <input type="submit" class="btn btn-danger" name="del" value="No" />
        </div>
    </form>

</div>




