<?php
/**
 * Created by PhpStorm.
 * User: Adam
 * Date: 19/11/2017
 * Time: 17:06
 */

namespace MediaBox\Controller;

use InvalidArgumentException;
use MediaBox\Model\Video;
use MediaBox\Model\VideoRepositoryInterface;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;

class MediaBoxController extends AbstractActionController
{
    private $videoRepository;

    public function __construct(VideoRepositoryInterface $videoRepository)
    {
        $this->videoRepository = $videoRepository;
    }

    public function indexAction()
    {
        return []; // TODO: Change the autogenerated stub
    }

    public function editAction()
    {
        //same as view at the moment
        $id = $this->params()->fromRoute('id');

        try{
            $video = $this->videoRepository->findVideo($id);
        } catch (InvalidArgumentException $exception){
            return $this->redirect()->toRoute('mediabox');
        }

        return new ViewModel([
            'video' => $video
        ]);
    }

    public function deleteAction()
    {
        $id = $this->params()->fromRoute('id');

        try{
            $video = $this->videoRepository->findVideo($id);
        } catch (InvalidArgumentException $exception){
            return $this->redirect()->toRoute('mediabox');
        }

        return new ViewModel([
            'video' => $video
        ]);
    }

    public function addAction()
    {
        return [];
    }

    public function videoAction()
    {
        $id = $this->params()->fromRoute('id');

        try{
            $video = $this->videoRepository->findVideo($id);
        } catch (InvalidArgumentException $exception){
            return $this->redirect()->toRoute('mediabox');
        }

        return new ViewModel([
            'video' => $video
        ]);

        //return ['video' => $video];
    }

}