<?php

$this->headTitle($this->video->getName());

//make tag iterator buffered
$tags = $this->tags->buffer();
$dt = new DateTime();
$dt->setTimestamp($this->video->getUploadedOn()); //<--- Pass a UNIX TimeStamp

//$time = '00:06:00';
//$timeInSeconds = strtotime($time) - strtotime('TODAY');
$timeInSeconds = $this->video->getDuration();

$duration = new DateTime();
$duration->setTimestamp($timeInSeconds);
?>

<style>
    .tags span { padding:4px; line-height: 3em; margin:2px; font-size: 14px;}
    video { position: relative; top: 0px;}

    .wrapper { margin: 50px; }

</style>

<body>
<div id="wrapper">

        <div class="panel panel-default">
            <div class="panel-heading videoTitle">

                <h2 class="text-center"><?= $this->video->getName() ?></h2>

            </div>
            <div class="panel-body videoBody">
                <video width="100%" height="auto" controls="" poster="/img/logocentre.png">
                    <source src="<?= $this->video->getUrl() ?>" type="video/mp4">
                </video>

                <h4 class="text-center">
                    <a class="btn btn-info" href="<?= $this->video->getUrl() ?>" download>Download <span class="glyphicon glyphicon-download"></span></a>
                    <a class="btn btn-info" href="<?= $this->url('mediabox/edit', ['id' => $this->video->getId()]) ?>">Edit <span class="glyphicon glyphicon-pencil"></span></a>
                    <a class="btn btn-info" href="<?= $this->url('mediabox/delete', ['id' => $this->video->getId()]) ?>">Delete <span class="glyphicon glyphicon-trash"></span></a>
                </h4>

                <div class="videoDescription">
                    <?= $this->video->getDescription(); ?>
                </div>
                <hr>
                <div class="videoMeta">
                    <label>Duration:</label> <?= $duration->format('H:i:s') ?><br>
                    <label>Uploaded on:</label> <?= $dt->format('dS F Y'); ?><br>
                        <label>Source:</label> <?= $this->video->getFormat() ?><br>
                </div>
                <hr>

                <div class=" tags">
                    <div>
                        <label class="h4">Film / TV / Series</label><br>
                        <?php foreach ($tags as $tag): ?>
                            <?php if($tag->getTagCategory() == 'Film / TV / Series'): ?>
                                <span class="label label-primary"><?= $tag->getTagName() ?></span>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </div>
                    <div>
                        <label class="h4">Departments</label><br>
                        <?php foreach ($tags as $tag): ?>
                            <?php if($tag->getTagCategory() == 'Departments'): ?>
                                <span class="label label-default"><?= $tag->getTagName() ?></span>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </div>
                    <div>
                        <label class="h4">Classification</label><br>
                        <?php foreach ($tags as $tag): ?>
                            <?php if($tag->getTagCategory() == 'Classification'): ?>
                                <span class="label label-success"><?= $tag->getTagName() ?></span>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </div>
                    <div>
                        <label class="h4">Categories</label><br>
                        <?php foreach ($tags as $tag): ?>
                            <?php if($tag->getTagCategory() == 'Categories'): ?>
                                <span class="label label-danger"><?= $tag->getTagName() ?></span>
                            <?php endif; ?>
                        <?php endforeach; ?>

                    </div>
                    <div>
                        <label class="h4">Custom tags</label><br>
                        <?php foreach ($tags as $tag): ?>
                            <?php if($tag->getTagCategory() == 'Custom tags'): ?>
                                <span class="label label-warning"><?= $tag->getTagName() ?></span>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

</html>