<?php
$this->headTitle("Add a video");
$tags = $this->tags->buffer();

$name = $form->get('name');
$url = $form->get('url');
$description = $form->get('description');
$format = $form->get('format');
?>

<style>
    .tags label { padding:4px;  margin:2px; font-size: 14px;}
    video { position: relative; top: 0px;}
    /* Hiding the checkbox, but allowing it to be focused */
    .badgebox
    {
        opacity: 0;
    }

    .badgebox + .badge
    {
        /* Move the check mark away when unchecked */
        text-indent: -999999px;
        /* Makes the badge's width stay the same checked and unchecked */
        width: 27px;
    }

    .badgebox:focus + .badge
    {
        /* Set something to make the badge looks focused */
        /* This really depends on the application, in my case it was: */

        /* Adding a light border */
        box-shadow: inset 0px 0px 5px;
        /* Taking the difference out of the padding */
    }

    .badgebox:checked + .badge
    {
        /* Move the check mark back when checked */
        text-indent: 0;
    }

</style>

<div id="wrapper">

    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading"><h3>Add a video</h3></div>
            <div class="panel-body">
                <?php
                echo $this->form()->openTag($form);
                ?>
                <div class="form-group">
                    <label for="comment">Video Name:</label>
                    <input class="form-control" type="text" name="name">
                    <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
                </div>

                <div class="form-group">
                    <label for="comment">Video URL:</label>
                    <input class="form-control" type="text" name="url">
                    <?= $this->formElementErrors()->render($url, ['class' => 'help-block']) ?>
                </div>

                <div class="form-group">
                    <label for="comment">Upload: (not in use/ignored)</label>
                    <input type="file" class="form-control">
                </div>

                <div class="form-group">
                    <label for="comment">Description:</label>
                    <textarea class="form-control" rows="5" id="description" name="description"></textarea>
                    <?= $this->formElementErrors()->render($description, ['class' => 'help-block']) ?>
                </div>

                <div class="form-group">
                    <label for="comment">Source:</label>
                    <input type="text" class="form-control" id="source" name="format">
                    <?= $this->formElementErrors()->render($format, ['class' => 'help-block']) ?>
                </div>

                <div class=" tags">

                    <div>
                        <label class="h4">Film / TV / Series</label><br>
                        <?php foreach ($tags as $tag): ?>
                            <?php if($tag->getTagCategory() == 'Film / TV / Series'): ?>
                                <label class="btn btn-primary"><span class=""><?= $tag->getTagName() ?> <input type="checkbox" id="tag<?= $tag->getTagName() ?>" name="selectedTags[]" class="badgebox" value="<?= $tag->getTagId() ?>"><span class="badge">&check;</span></span></label>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </div>
                    <div>
                        <label class="h4">Departments</label><br>
                        <?php foreach ($tags as $tag): ?>
                            <?php if($tag->getTagCategory() == 'Departments'): ?>
                                <label class="btn btn-default"><span class="""><?= $tag->getTagName() ?> <input type="checkbox" id="tag<?= $tag->getTagName() ?>" name="selectedTags[]" class="badgebox" value="<?= $tag->getTagId() ?>"><span class="badge">&check;</span></span></label>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </div>
                    <div>
                        <label class="h4">Classification</label><br>
                        <?php foreach ($tags as $tag): ?>
                            <?php if($tag->getTagCategory() == 'Classification'): ?>
                                <label class="btn btn-success"><span class="""><?= $tag->getTagName() ?> <input type="radio" id="tag<?= $tag->getTagName() ?>" name="selectedTags[]" class="badgebox" value="<?= $tag->getTagId() ?>"><span class="badge">&check;</span></span></label>
                            <?php endif; ?>
                        <?php endforeach; ?>    </div>
                    <div>
                        <label class="h4">Categories</label><br>
                        <?php foreach ($tags as $tag): ?>
                            <?php if($tag->getTagCategory() == 'Categories'): ?>
                                <label class="btn btn-danger"><span class="""><?= $tag->getTagName() ?> <input type="checkbox" id="tag<?= $tag->getTagName() ?>" name="selectedTags[]" class="badgebox" value="<?= $tag->getTagId() ?>"><span class="badge">&check;</span></span></label>
                            <?php endif; ?>
                        <?php endforeach; ?>                        </div>
                    <div>
                        <label class="h4">Custom tags</label><br>
                        <?php foreach ($tags as $tag): ?>
                            <?php if($tag->getTagCategory() == 'Custom tags'): ?>
                                <label class="btn btn-warning"><span class="""><?= $tag->getTagName() ?> <input type="checkbox" id="tag<?= $tag->getTagName() ?>" name="selectedTags[]" class="badgebox" value="<?= $tag->getTagId() ?>"><span class="badge">&check;</span></span></label>
                            <?php endif; ?>
                        <?php endforeach; ?>
                        <div class="input-group">
                            <input size="8" type="text" class="form-control" placeholder="Add custom tags...">
                            <span class="input-group-btn">
							<button type="submit" class="btn btn-warning">
								<span class="glyphicon glyphicon-plus">
									<span class="sr-only">Add custom tags...</span>
								</span>
							</button>
						    </span>
                        </div>
                        <br>
                        <input type="submit" class="btn btn-success" value="Add to MediaBox">
                        <button type="cancel" class="btn btn-danger">Cancel</button>
                    </div>

                </div>
                <?php
                echo $this->form()->openTag($form);
                ?>

            </div>
        </div>
    </div>
</div>